version: "3.1"

recipe: default.v1

assistant_id: 20240502-120001-violent-vibration

language: en

pipeline:
- name: WhitespaceTokenizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100

policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: UnexpecTEDIntentPolicy
  epochs: 100

actions:
  - actions.bank_actions
